# Generated by Django 4.0.2 on 2022-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(related_name='question_parent', to='djangoapp.Question'),
        ),
    ]
